acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/routes/__init__.py
# le fichier __init__.py permet l'import des fichiers contenus dans le dossier routes.
# on y indique les emplacements des fichiers que contient le dossier routes


from flask import Blueprint
routes = Blueprint('routes', __name__)



from .index import *
from .acar1.acar1_1 import *
from .acar1.acar1_2 import *
from .acar1.acar1_3 import *
from .acar2.acar2 import *

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/routes/index.py
from flask import Flask, render_template, request, redirect, url_for, session,flash
from . import routes


@routes.route("/")
def index():
    return render_template("index.html")

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/acar1/acar1.2.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} ACAR1 {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1.1') }}">Page1</a>
<a href="{{ url_for('routes.f_acar1.2') }}">Page2</a>




{% for tache in donnees if tache['slide'] == 1 %}
    
    {% if tache['sablier']: %}
    <form onsubmit="modifier(event, {{tache['id']}})">
        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit"   class="btn btn-primary accomplie-{{ tache['accomplie'] }}">
                {{ tache['label'] }}
            </button>
        </div>
        {{ tache['etat_sablier'] }}
        <div>


        </div>
    </form>
    {% else %}
    <form onsubmit="modifier(event, {{tache['id']}})">
        <div class="d-grid gap-2 col-6 mx-auto">
            <button id="button_{{ tache['id'] }}" type="submit" class="btn btn-primary accomplie-{{ tache['accomplie'] }}">
                {{ tache['label'] }}
            </button>
        </div>
        <span id = "id_sablier{{tache['id']}}">{{ tache['etat_sablier'] }}</span> 
        <div>


        </div>
    </form>
    {% endif %}
{% endfor %}


<h2>Chronomètre général</h2>

<p><span id="valeur_chrono_general">{{valeur_chrono_general}}</span></p>



<script>
     function modifier(event, tache_id) {
        event.preventDefault();
        fetch('/modifier/' + tache_id, {
            method: 'POST'
        })
        .then(response => response.json())
        .then(data => {
            console.log('Réponse du serveur :', data);  // Débogage

            // Parcourez la liste de dictionnaires pour trouver celui avec l'ID correspondant
            var donnees = data.donnees;
            var accomplieValue = -1;  // Valeur par défaut, assurez-vous qu'elle ne correspond pas à une valeur valide

            for (var i = 0; i < donnees.length; i++) {
                if (donnees[i].id === tache_id) {
                    accomplieValue = donnees[i].accomplie;
                    break;  // Sortez de la boucle dès que vous trouvez le dictionnaire
                }
            }

            // Assurez-vous que l'ID correspond à un élément dans le DOM
            var spanElement = document.getElementById(tache_id);

            if (spanElement && accomplieValue !== -1) {
                spanElement.innerText = accomplieValue;
            } else {
                console.error('Élément avec l\'ID ' + tache_id + ' non trouvé ou valeur accomplie invalide.');
            }
        })
        .catch(error => {
            console.error('Erreur lors de la requête fetch :', error);
        });
    }

    function maj() {
        
        fetch('/maj')  
        .then(response => response.json())
        .then(data => {
            console.log('Réponse du serveur :', data);  // Débogage
            var donnees = data.donnees;
            var sabliers = data.sabliers;
            for (var i = 0; i < sabliers.length; i++) {
                
                if (sabliers[i].isRunning === "true") {
                    id = "id_sablier"+sabliers[i].id;
                    
                    document.getElementById(id).innerText = data.sabliers[i].temps_restant ;
                }

            }

            for (var i = 0; i < donnees.length; i++) {
                var tache_id = data.donnees[i].id;
                var accomplieValue = data.donnees[i].accomplie;
                var buttonElement = document.getElementById('button_' + tache_id);
               

                if (buttonElement && accomplieValue !== undefined) {
                    // Mise à jour de la classe CSS du bouton
                    buttonElement.classList.remove('accomplie-0', 'accomplie-1');
                    buttonElement.classList.add('accomplie-' + accomplieValue);
                } else {
                    console.error('Bouton avec l\'ID button_' + tache_id + ' non trouvé ou valeur accomplie invalide.');
                }
                                    
            }
        });
    }

        function updateChrono_general() {
            fetch('/maj_chrono_general')  
                .then(response => response.json())
                .then(data => {
                   
                    document.getElementById('valeur_chrono_general').innerText = data.valeur_chrono_general ;
                });
        }


        setInterval(() => {
            
            updateChrono_general();
            
        }, 1000);

        setInterval(() => {
            
            maj();
            
        }, 1000);



</script>

{% endblock %}

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/acar1/acar1_1.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} ACAR1 {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1_1') }}">Page1</a>
<a href="{{ url_for('routes.f_acar1_2') }}">Page2</a>




{% for tache in donnees if tache['slide'] == 1 %}
    
    {% if tache['sablier']: %}
    <form onsubmit="modifier(event, {{tache['id']}})">
        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit"   class="btn btn-primary accomplie-{{ tache['accomplie'] }}">
                {{ tache['label'] }}
            </button>
        </div>
        {{ tache['etat_sablier'] }}
        <div>


        </div>
    </form>
    {% else %}
    <form onsubmit="modifier(event, {{tache['id']}})">
        <div class="d-grid gap-2 col-6 mx-auto">
            <button id="button_{{ tache['id'] }}" type="submit" class="btn btn-primary accomplie-{{ tache['accomplie'] }}">
                {{ tache['label'] }}
            </button>
        </div>
        <span id = "id_sablier{{tache['id']}}">{{ tache['etat_sablier'] }}</span> 
        <div>


        </div>
    </form>
    {% endif %}
{% endfor %}


<h2>Chronomètre général</h2>

<p><span id="valeur_chrono_general">{{valeur_chrono_general}}</span></p>



<script>
     function modifier(event, tache_id) {
        event.preventDefault();
        fetch('/modifier/' + tache_id, {
            method: 'POST'
        })
        .then(response => response.json())
        .then(data => {
            console.log('Réponse du serveur :', data);  // Débogage

            // Parcourez la liste de dictionnaires pour trouver celui avec l'ID correspondant
            var donnees = data.donnees;
            var accomplieValue = -1;  // Valeur par défaut, assurez-vous qu'elle ne correspond pas à une valeur valide

            for (var i = 0; i < donnees.length; i++) {
                if (donnees[i].id === tache_id) {
                    accomplieValue = donnees[i].accomplie;
                    break;  // Sortez de la boucle dès que vous trouvez le dictionnaire
                }
            }

            // Assurez-vous que l'ID correspond à un élément dans le DOM
            var spanElement = document.getElementById(tache_id);

            if (spanElement && accomplieValue !== -1) {
                spanElement.innerText = accomplieValue;
            } else {
                console.error('Élément avec l\'ID ' + tache_id + ' non trouvé ou valeur accomplie invalide.');
            }
        })
        .catch(error => {
            console.error('Erreur lors de la requête fetch :', error);
        });
    }

    function maj() {
        
        fetch('/maj')  
        .then(response => response.json())
        .then(data => {
            console.log('Réponse du serveur :', data);  // Débogage
            var donnees = data.donnees;
            var sabliers = data.sabliers;
            for (var i = 0; i < sabliers.length; i++) {
                
                if (sabliers[i].isRunning === "true") {
                    id = "id_sablier"+sabliers[i].id;
                    
                    document.getElementById(id).innerText = data.sabliers[i].temps_restant ;
                }

            }

            for (var i = 0; i < donnees.length; i++) {
                var tache_id = data.donnees[i].id;
                var accomplieValue = data.donnees[i].accomplie;
                var buttonElement = document.getElementById('button_' + tache_id);
               

                if (buttonElement && accomplieValue !== undefined) {
                    // Mise à jour de la classe CSS du bouton
                    buttonElement.classList.remove('accomplie-0', 'accomplie-1');
                    buttonElement.classList.add('accomplie-' + accomplieValue);
                } else {
                    console.error('Bouton avec l\'ID button_' + tache_id + ' non trouvé ou valeur accomplie invalide.');
                }
                                    
            }
        });
    }

        function updateChrono_general() {
            fetch('/maj_chrono_general')  
                .then(response => response.json())
                .then(data => {
                   
                    document.getElementById('valeur_chrono_general').innerText = data.valeur_chrono_general ;
                });
        }


        setInterval(() => {
            
            updateChrono_general();
            
        }, 1000);

        setInterval(() => {
            
            maj();
            
        }, 1000);



</script>

{% endblock %}

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/acar1/acar1_2.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} ACAR1 {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1_1') }}">Page1</a>
<a href="{{ url_for('routes.f_acar1_2') }}">Page2</a>




{% for tache in donnees if tache['slide'] == 2 %}
    
    {% if tache['sablier']: %}
    <form onsubmit="modifier(event, {{tache['id']}})">
        <div class="d-grid gap-2 col-6 mx-auto">
            <button type="submit"   class="btn btn-primary accomplie-{{ tache['accomplie'] }}">
                {{ tache['label'] }}
            </button>
        </div>
        {{ tache['etat_sablier'] }}
        <div>


        </div>
    </form>
    {% else %}
    <form onsubmit="modifier(event, {{tache['id']}})">
        <div class="d-grid gap-2 col-6 mx-auto">
            <button id="button_{{ tache['id'] }}" type="submit" class="btn btn-primary accomplie-{{ tache['accomplie'] }}">
                {{ tache['label'] }}
            </button>
        </div>
        <span id = "id_sablier{{tache['id']}}">{{ tache['etat_sablier'] }}</span> 
        <div>


        </div>
    </form>
    {% endif %}
{% endfor %}


<h2>Chronomètre général</h2>

<p><span id="valeur_chrono_general">{{valeur_chrono_general}}</span></p>



<script>
     function modifier(event, tache_id) {
        event.preventDefault();
        fetch('/modifier/' + tache_id, {
            method: 'POST'
        })
        .then(response => response.json())
        .then(data => {
            console.log('Réponse du serveur :', data);  // Débogage

            // Parcourez la liste de dictionnaires pour trouver celui avec l'ID correspondant
            var donnees = data.donnees;
            var accomplieValue = -1;  // Valeur par défaut, assurez-vous qu'elle ne correspond pas à une valeur valide

            for (var i = 0; i < donnees.length; i++) {
                if (donnees[i].id === tache_id) {
                    accomplieValue = donnees[i].accomplie;
                    break;  // Sortez de la boucle dès que vous trouvez le dictionnaire
                }
            }

            // Assurez-vous que l'ID correspond à un élément dans le DOM
            var spanElement = document.getElementById(tache_id);

            if (spanElement && accomplieValue !== -1) {
                spanElement.innerText = accomplieValue;
            } else {
                console.error('Élément avec l\'ID ' + tache_id + ' non trouvé ou valeur accomplie invalide.');
            }
        })
        .catch(error => {
            console.error('Erreur lors de la requête fetch :', error);
        });
    }

    function maj() {
        
        fetch('/maj')  
        .then(response => response.json())
        .then(data => {
            console.log('Réponse du serveur :', data);  // Débogage
            var donnees = data.donnees;
            var sabliers = data.sabliers;
            for (var i = 0; i < sabliers.length; i++) {
                
                if (sabliers[i].isRunning === "true") {
                    id = "id_sablier"+sabliers[i].id;
                    
                    document.getElementById(id).innerText = data.sabliers[i].temps_restant ;
                }

            }

            for (var i = 0; i < donnees.length; i++) {
                var tache_id = data.donnees[i].id;
                var accomplieValue = data.donnees[i].accomplie;
                var buttonElement = document.getElementById('button_' + tache_id);
               

                if (buttonElement && accomplieValue !== undefined) {
                    // Mise à jour de la classe CSS du bouton
                    buttonElement.classList.remove('accomplie-0', 'accomplie-1');
                    buttonElement.classList.add('accomplie-' + accomplieValue);
                } else {
                    console.error('Bouton avec l\'ID button_' + tache_id + ' non trouvé ou valeur accomplie invalide.');
                }
                                    
            }
        });
    }

        function updateChrono_general() {
            fetch('/maj_chrono_general')  
                .then(response => response.json())
                .then(data => {
                   
                    document.getElementById('valeur_chrono_general').innerText = data.valeur_chrono_general ;
                });
        }


        setInterval(() => {
            
            updateChrono_general();
            
        }, 1000);

        setInterval(() => {
            
            maj();
            
        }, 1000);



</script>

{% endblock %}

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/acar1/acar1_3.html
{% extends 'base.html' %}

{% block content %}

<h1>{% block title %} ACAR1 page2  {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1_1') }}">Acar1</a>

<h1>Page 1</h1>

<h2>Chronomètre général</h2>

<p><span id="valeur_chrono_general">{{valeur_chrono_general}}</span></p>

<h2>Sabliers</h2>

<h1>compte à rebours massage : </h1>
    <button id="start_s_massage">Démarrer le compte à rebours massage cardiaque</button>
    <p>Temps écoulé pour le massage cardiaque : <span id="temps_restant_s_massage">{{temps_restant_s_massage }}</span> secondes restantes</p>
    
<h1>compte à rebours massage : </h1>
    <button id="start_s_injection">Démarrer le compte à rebours Injection</button>
    <p>Temps écoulé pour le massage cardiaque : <span id="temps_restant_s_injection">{{temps_restant_s_injection }}</span> secondes restantes</p>
    
    
<script>

        
        function start_s_massage() {
            fetch('/start_s_massage')  
                .then(response => response.json())
                .then(data => {
                    
                    document.getElementById('temps_restant_s_massage').innerText =data.temps_restant_s_massage ;
                });
        }
        function start_s_injection() {
            fetch('/start_s_injection')  
                .then(response => response.json())
                .then(data => {
                    
                    document.getElementById('temps_restant_s_injection').innerText =data.temps_restant_s_injection ;
                });
        }
        function updateChrono_general() {
            fetch('/maj_chrono_general')  
                .then(response => response.json())
                .then(data => {
                   
                    document.getElementById('valeur_chrono_general').innerText = data.valeur_chrono_general ;
                });
        }

        function update_s_massage() {
            fetch('/maj_s')  
                .then(response => response.json())
                .then(data => {
                    
                    document.getElementById('temps_restant_s_massage').innerText = data.temps_restant_s_massage ;
                });
        }

        function update_s_injection() {
            fetch('/maj_s')  
                .then(response => response.json())
                .then(data => {
                   
                    document.getElementById('temps_restant_s_injection').innerText = data.temps_restant_s_injection ;
                });
        }

        setInterval(() => {
            fetch('/maj_s')
                .then(response => response.json())
                .then(data => {
                    if (data.s_massageRunning === 'true') {
                    update_s_massage();
                }
            })
        }, 1000);

        setInterval(() => {
            fetch('/maj_s')
                .then(response => response.json())
                .then(data => {
                    if (data.s_injectionRunning === 'true') {
                    update_s_injection();
                }
            })
        }, 1000);


        setInterval(() => {
            
            updateChrono_general();
            
        }, 1000);

        document.getElementById('start_s_massage').addEventListener('click', function() {
            // Lorsque le bouton est cliqué, changer l'état du timer et démarrer le compte à rebours
            s_massageRunning = 'true';
            start_s_massage();
        });

        document.getElementById('start_s_injection').addEventListener('click', function() {
            // Lorsque le bouton est cliqué, changer l'état du timer et démarrer le compte à rebours
            s_injectionRunning = 'true';
            start_s_injection();
        });

    </script>
{% endblock %}

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/acar2/acar2.html
{% extends "base.html" %}

{% block content %}

<h3>{% block title %} ACAR2 {% endblock %}</h3>

    
{% endblock %}

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon appli</title>
    <link rel="stylesheet"  href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block css %}
    <style>
        .accomplie-0 {
            background-color: red;
        }

        .accomplie-1 {
            background-color: green;
        }
    </style>
    {% endblock %}
</head>
<body>
    <script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <nav id="navbar">
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo" width="50">
        <ul id="navbar-items">
            <li class="navbar-item">
                <a href="{{ url_for('routes.index') }}">Accueil</a>
            </li>
            
            
            <li class="navbar-item">
                <a href="{{ url_for('routes.f_acar1_1') }}">Acar1</a>
            </li>
           
          
        </ul> 
    </nav>
    
    <div id="container">
        {% block content %}{% endblock %}
    </div>
    
</body>
</html>

acar.0.91_boutons_et_chrono_bouton_associe_a_chrono/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Accueil</h1>
<p> bienvenue sur ACAR !</p>
{% endblock %}